export interface CurrencyConfig {
  code: string;
  name: string;
  symbol: string;
  digits: number;
  groupSep: string;
  decimalSep: string;
}

export const CURRENCIES: CurrencyConfig[] = [
  // --- A ---
  {
    code: "AED",
    name: "UAE Dirham",
    symbol: "د.إ",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "AFN",
    name: "Afghan Afghani",
    symbol: "؋",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "ALL",
    name: "Albanian Lek",
    symbol: "L",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "AMD",
    name: "Armenian Dram",
    symbol: "֏",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "ANG",
    name: "Netherlands Antillean Guilder",
    symbol: "ƒ",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "AOA",
    name: "Angolan Kwanza",
    symbol: "Kz",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "ARS",
    name: "Argentine Peso",
    symbol: "$",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "AUD",
    name: "Australian Dollar",
    symbol: "A$",
    digits: 2,
    groupSep: " ",
    decimalSep: ".",
  },

  // --- B ---
  {
    code: "BAM",
    name: "Bosnia-Herzegovina Mark",
    symbol: "KM",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "BBD",
    name: "Barbadian Dollar",
    symbol: "$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "BDT",
    name: "Bangladeshi Taka",
    symbol: "৳",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "BGN",
    name: "Bulgarian Lev",
    symbol: "лв",
    digits: 2,
    groupSep: " ",
    decimalSep: ",",
  },
  {
    code: "BHD",
    name: "Bahraini Dinar",
    symbol: ".د.ب",
    digits: 3,
    groupSep: ",",
    decimalSep: ".",
  }, // 3 Digits
  {
    code: "BIF",
    name: "Burundian Franc",
    symbol: "FBu",
    digits: 0,
    groupSep: ".",
    decimalSep: "",
  }, // 0 Digits
  {
    code: "BMD",
    name: "Bermudan Dollar",
    symbol: "$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "BND",
    name: "Brunei Dollar",
    symbol: "$",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "BOB",
    name: "Bolivian Boliviano",
    symbol: "Bs.",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "BRL",
    name: "Brazilian Real",
    symbol: "R$",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "BSD",
    name: "Bahamian Dollar",
    symbol: "$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "BTN",
    name: "Bhutanese Ngultrum",
    symbol: "Nu.",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "BWP",
    name: "Botswanan Pula",
    symbol: "P",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "BYN",
    name: "Belarusian Ruble",
    symbol: "Br",
    digits: 2,
    groupSep: " ",
    decimalSep: ",",
  },
  {
    code: "BZD",
    name: "Belize Dollar",
    symbol: "BZ$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },

  // --- C ---
  {
    code: "CAD",
    name: "Canadian Dollar",
    symbol: "C$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "CDF",
    name: "Congolese Franc",
    symbol: "FC",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "CHF",
    name: "Swiss Franc",
    symbol: "CHF",
    digits: 2,
    groupSep: "'",
    decimalSep: ".",
  }, // Swiss style '
  {
    code: "CLP",
    name: "Chilean Peso",
    symbol: "$",
    digits: 0,
    groupSep: ".",
    decimalSep: "",
  }, // 0 Digits
  {
    code: "CNY",
    name: "Chinese Yuan",
    symbol: "¥",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "COP",
    name: "Colombian Peso",
    symbol: "$",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "CRC",
    name: "Costa Rican Colón",
    symbol: "₡",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "CUP",
    name: "Cuban Peso",
    symbol: "$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "CVE",
    name: "Cape Verdean Escudo",
    symbol: "$",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "CZK",
    name: "Czech Koruna",
    symbol: "Kč",
    digits: 2,
    groupSep: " ",
    decimalSep: ",",
  },

  // --- D ---
  {
    code: "DJF",
    name: "Djiboutian Franc",
    symbol: "Fdj",
    digits: 0,
    groupSep: " ",
    decimalSep: "",
  }, // 0 Digits
  {
    code: "DKK",
    name: "Danish Krone",
    symbol: "kr",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "DOP",
    name: "Dominican Peso",
    symbol: "RD$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "DZD",
    name: "Algerian Dinar",
    symbol: "د.ج",
    digits: 2,
    groupSep: " ",
    decimalSep: ",",
  },

  // --- E ---
  {
    code: "EGP",
    name: "Egyptian Pound",
    symbol: "£",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "ERN",
    name: "Eritrean Nakfa",
    symbol: "Nfk",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "ETB",
    name: "Ethiopian Birr",
    symbol: "Br",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "EUR",
    name: "Euro",
    symbol: "€",
    digits: 2,
    groupSep: " ",
    decimalSep: ",",
  }, // European Standard

  // --- F ---
  {
    code: "FJD",
    name: "Fijian Dollar",
    symbol: "$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "FKP",
    name: "Falkland Islands Pound",
    symbol: "£",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },

  // --- G ---
  {
    code: "GBP",
    name: "British Pound Sterling",
    symbol: "£",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "GEL",
    name: "Georgian Lari",
    symbol: "₾",
    digits: 2,
    groupSep: " ",
    decimalSep: ",",
  },
  {
    code: "GHS",
    name: "Ghanaian Cedi",
    symbol: "GH₵",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "GIP",
    name: "Gibraltar Pound",
    symbol: "£",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "GMD",
    name: "Gambian Dalasi",
    symbol: "D",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "GNF",
    name: "Guinean Franc",
    symbol: "FG",
    digits: 0,
    groupSep: ".",
    decimalSep: "",
  }, // 0 Digits
  {
    code: "GTQ",
    name: "Guatemalan Quetzal",
    symbol: "Q",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "GYD",
    name: "Guyanaese Dollar",
    symbol: "$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },

  // --- H ---
  {
    code: "HKD",
    name: "Hong Kong Dollar",
    symbol: "HK$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "HNL",
    name: "Honduran Lempira",
    symbol: "L",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "HRK",
    name: "Croatian Kuna",
    symbol: "kn",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "HTG",
    name: "Haitian Gourde",
    symbol: "G",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "HUF",
    name: "Hungarian Forint",
    symbol: "Ft",
    digits: 2,
    groupSep: " ",
    decimalSep: ",",
  },

  // --- I ---
  {
    code: "IDR",
    name: "Indonesian Rupiah",
    symbol: "Rp",
    digits: 0,
    groupSep: ".",
    decimalSep: "",
  }, // Usually 0 digits
  {
    code: "ILS",
    name: "Israeli New Shekel",
    symbol: "₪",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "INR",
    name: "Indian Rupee",
    symbol: "₹",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "IQD",
    name: "Iraqi Dinar",
    symbol: "ع.د",
    digits: 3,
    groupSep: ",",
    decimalSep: ".",
  }, // 3 Digits
  {
    code: "IRR",
    name: "Iranian Rial",
    symbol: "﷼",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "ISK",
    name: "Icelandic Króna",
    symbol: "kr",
    digits: 0,
    groupSep: ".",
    decimalSep: "",
  }, // 0 Digits

  // --- J ---
  {
    code: "JMD",
    name: "Jamaican Dollar",
    symbol: "J$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "JOD",
    name: "Jordanian Dinar",
    symbol: "د.ا",
    digits: 3,
    groupSep: ",",
    decimalSep: ".",
  }, // 3 Digits
  {
    code: "JPY",
    name: "Japanese Yen",
    symbol: "¥",
    digits: 0,
    groupSep: ",",
    decimalSep: "",
  }, // 0 Digits

  // --- K ---
  {
    code: "KES",
    name: "Kenyan Shilling",
    symbol: "KSh",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "KGS",
    name: "Kyrgystani Som",
    symbol: "с",
    digits: 2,
    groupSep: " ",
    decimalSep: "-",
  },
  {
    code: "KHR",
    name: "Cambodian Riel",
    symbol: "៛",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "KMF",
    name: "Comorian Franc",
    symbol: "CF",
    digits: 0,
    groupSep: ",",
    decimalSep: "",
  }, // 0 Digits
  {
    code: "KRW",
    name: "South Korean Won",
    symbol: "₩",
    digits: 0,
    groupSep: ",",
    decimalSep: "",
  }, // 0 Digits
  {
    code: "KWD",
    name: "Kuwaiti Dinar",
    symbol: "د.ك",
    digits: 3,
    groupSep: ",",
    decimalSep: ".",
  }, // 3 Digits
  {
    code: "KYD",
    name: "Cayman Islands Dollar",
    symbol: "$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "KZT",
    name: "Kazakhstani Tenge",
    symbol: "₸",
    digits: 2,
    groupSep: " ",
    decimalSep: ",",
  },

  // --- L ---
  {
    code: "LAK",
    name: "Laotian Kip",
    symbol: "₭",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "LBP",
    name: "Lebanese Pound",
    symbol: "ل.ل",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "LKR",
    name: "Sri Lankan Rupee",
    symbol: "Rs",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "LRD",
    name: "Liberian Dollar",
    symbol: "$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "LSL",
    name: "Lesotho Loti",
    symbol: "L",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "LYD",
    name: "Libyan Dinar",
    symbol: "ل.د",
    digits: 3,
    groupSep: ",",
    decimalSep: ".",
  }, // 3 Digits

  // --- M ---
  {
    code: "MAD",
    name: "Moroccan Dirham",
    symbol: "د.م.",
    digits: 2,
    groupSep: " ",
    decimalSep: ",",
  },
  {
    code: "MDL",
    name: "Moldovan Leu",
    symbol: "L",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "MGA",
    name: "Malagasy Ariary",
    symbol: "Ar",
    digits: 2,
    groupSep: " ",
    decimalSep: ".",
  },
  {
    code: "MKD",
    name: "Macedonian Denar",
    symbol: "ден",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "MMK",
    name: "Burmese Kyat",
    symbol: "K",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "MNT",
    name: "Mongolian Tugrik",
    symbol: "₮",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "MOP",
    name: "Macanese Pataca",
    symbol: "MOP$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "MUR",
    name: "Mauritian Rupee",
    symbol: "₨",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "MVR",
    name: "Maldivian Rufiyaa",
    symbol: ".ރ",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "MWK",
    name: "Malawian Kwacha",
    symbol: "MK",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "MXN",
    name: "Mexican Peso",
    symbol: "$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "MYR",
    name: "Malaysian Ringgit",
    symbol: "RM",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "MZN",
    name: "Mozambican Metical",
    symbol: "MT",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },

  // --- N ---
  {
    code: "NAD",
    name: "Namibian Dollar",
    symbol: "$",
    digits: 2,
    groupSep: " ",
    decimalSep: ",",
  },
  {
    code: "NGN",
    name: "Nigerian Naira",
    symbol: "₦",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "NIO",
    name: "Nicaraguan Córdoba",
    symbol: "C$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "NOK",
    name: "Norwegian Krone",
    symbol: "kr",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "NPR",
    name: "Nepalese Rupee",
    symbol: "₨",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "NZD",
    name: "New Zealand Dollar",
    symbol: "NZ$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },

  // --- O ---
  {
    code: "OMR",
    name: "Omani Rial",
    symbol: "ر.ع.",
    digits: 3,
    groupSep: ",",
    decimalSep: ".",
  }, // 3 Digits

  // --- P ---
  {
    code: "PAB",
    name: "Panamanian Balboa",
    symbol: "B/.",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "PEN",
    name: "Peruvian Sol",
    symbol: "S/",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "PGK",
    name: "Papua New Guinean Kina",
    symbol: "K",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "PHP",
    name: "Philippine Peso",
    symbol: "₱",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "PKR",
    name: "Pakistani Rupee",
    symbol: "₨",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "PLN",
    name: "Polish Zloty",
    symbol: "zł",
    digits: 2,
    groupSep: " ",
    decimalSep: ",",
  },
  {
    code: "PYG",
    name: "Paraguayan Guarani",
    symbol: "₲",
    digits: 0,
    groupSep: ".",
    decimalSep: "",
  }, // 0 Digits

  // --- Q ---
  {
    code: "QAR",
    name: "Qatari Riyal",
    symbol: "ر.ق",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },

  // --- R ---
  {
    code: "RON",
    name: "Romanian Leu",
    symbol: "lei",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "RSD",
    name: "Serbian Dinar",
    symbol: "дин.",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "RUB",
    name: "Russian Ruble",
    symbol: "₽",
    digits: 2,
    groupSep: " ",
    decimalSep: ",",
  },
  {
    code: "RWF",
    name: "Rwandan Franc",
    symbol: "FRw",
    digits: 0,
    groupSep: " ",
    decimalSep: "",
  }, // 0 Digits

  // --- S ---
  {
    code: "SAR",
    name: "Saudi Riyal",
    symbol: "﷼",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "SBD",
    name: "Solomon Islands Dollar",
    symbol: "$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "SCR",
    name: "Seychellois Rupee",
    symbol: "₨",
    digits: 2,
    groupSep: " ",
    decimalSep: ".",
  },
  {
    code: "SDG",
    name: "Sudanese Pound",
    symbol: "£",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "SEK",
    name: "Swedish Krona",
    symbol: "kr",
    digits: 2,
    groupSep: " ",
    decimalSep: ",",
  },
  {
    code: "SGD",
    name: "Singapore Dollar",
    symbol: "S$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "SHP",
    name: "Saint Helena Pound",
    symbol: "£",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "SLE",
    name: "Sierra Leonean Leone",
    symbol: "Le",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "SOS",
    name: "Somali Shilling",
    symbol: "Sh",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "SRD",
    name: "Surinamese Dollar",
    symbol: "$",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "SSP",
    name: "South Sudanese Pound",
    symbol: "£",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "STN",
    name: "São Tomé and Príncipe Dobra",
    symbol: "Db",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "SYP",
    name: "Syrian Pound",
    symbol: "£",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "SZL",
    name: "Eswatini Lilangeni",
    symbol: "L",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },

  // --- T ---
  {
    code: "THB",
    name: "Thai Baht",
    symbol: "฿",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "TJS",
    name: "Tajikistani Somoni",
    symbol: "SM",
    digits: 2,
    groupSep: " ",
    decimalSep: ".",
  },
  {
    code: "TMT",
    name: "Turkmenistani Manat",
    symbol: "T",
    digits: 2,
    groupSep: " ",
    decimalSep: ",",
  },
  {
    code: "TND",
    name: "Tunisian Dinar",
    symbol: "د.ت",
    digits: 3,
    groupSep: " ",
    decimalSep: ",",
  }, // 3 Digits
  {
    code: "TOP",
    name: "Tongan Pa'anga",
    symbol: "T$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "TRY",
    name: "Turkish Lira",
    symbol: "₺",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "TTD",
    name: "Trinidad and Tobago Dollar",
    symbol: "TT$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "TWD",
    name: "New Taiwan Dollar",
    symbol: "NT$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "TZS",
    name: "Tanzanian Shilling",
    symbol: "Sh",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },

  // --- U ---
  {
    code: "UAH",
    name: "Ukrainian Hryvnia",
    symbol: "₴",
    digits: 2,
    groupSep: " ",
    decimalSep: ",",
  },
  {
    code: "UGX",
    name: "Ugandan Shilling",
    symbol: "USh",
    digits: 0,
    groupSep: ",",
    decimalSep: "",
  }, // 0 Digits
  {
    code: "USD",
    name: "United States Dollar",
    symbol: "$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "UYU",
    name: "Uruguayan Peso",
    symbol: "$U",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "UZS",
    name: "Uzbekistani So'm",
    symbol: "лв",
    digits: 2,
    groupSep: " ",
    decimalSep: ",",
  },

  // --- V ---
  {
    code: "VES",
    name: "Venezuelan Bolívar",
    symbol: "Bs.",
    digits: 2,
    groupSep: ".",
    decimalSep: ",",
  },
  {
    code: "VND",
    name: "Vietnamese Dong",
    symbol: "₫",
    digits: 0,
    groupSep: ".",
    decimalSep: "",
  }, // 0 Digits
  {
    code: "VUV",
    name: "Vanuatu Vatu",
    symbol: "VT",
    digits: 0,
    groupSep: ",",
    decimalSep: "",
  }, // 0 Digits

  // --- W ---
  {
    code: "WST",
    name: "Samoan Tala",
    symbol: "T",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },

  // --- X ---
  {
    code: "XAF",
    name: "Central African CFA Franc",
    symbol: "FCFA",
    digits: 0,
    groupSep: " ",
    decimalSep: "",
  }, // 0 Digits
  {
    code: "XCD",
    name: "East Caribbean Dollar",
    symbol: "$",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },
  {
    code: "XOF",
    name: "West African CFA Franc",
    symbol: "CFA",
    digits: 0,
    groupSep: " ",
    decimalSep: "",
  }, // 0 Digits
  {
    code: "XPF",
    name: "CFP Franc",
    symbol: "₣",
    digits: 0,
    groupSep: " ",
    decimalSep: "",
  }, // 0 Digits

  // --- Y ---
  {
    code: "YER",
    name: "Yemeni Rial",
    symbol: "﷼",
    digits: 2,
    groupSep: ",",
    decimalSep: ".",
  },

  // --- Z ---
  {
    code: "ZAR",
    name: "South African Rand",
    symbol: "R",
    digits: 2,
    groupSep: " ",
    decimalSep: ",",
  },
  {
    code: "ZMW",
    name: "Zambian Kwacha",
    symbol: "ZK",
    digits: 2,
    groupSep: " ",
    decimalSep: ".",
  },
  {
    code: "ZWL",
    name: "Zimbabwean Dollar",
    symbol: "$",
    digits: 2,
    groupSep: " ",
    decimalSep: ".",
  },
];
