/**
 * @fileoverview Country Phone Codes
 * A comprehensive list of countries, ISO codes, and dialing prefixes.
 * Used for the PhoneInput component.
 */

export const PHONE_CODE_COUNTRIES = [
  { code: "AF", label: "+93", name: "Afghanistan" },
  { code: "AL", label: "+355", name: "Albania" },
  { code: "DZ", label: "+213", name: "Algeria" },
  { code: "AR", label: "+54", name: "Argentina" },
  { code: "AM", label: "+374", name: "Armenia" },
  { code: "AU", label: "+61", name: "Australia" },
  { code: "AT", label: "+43", name: "Austria" },
  { code: "AZ", label: "+994", name: "Azerbaijan" },
  { code: "BH", label: "+973", name: "Bahrain" },
  { code: "BD", label: "+880", name: "Bangladesh" },
  { code: "BY", label: "+375", name: "Belarus" },
  { code: "BE", label: "+32", name: "Belgium" },
  { code: "BO", label: "+591", name: "Bolivia" },
  { code: "BA", label: "+387", name: "Bosnia and Herzegovina" },
  { code: "BR", label: "+55", name: "Brazil" },
  { code: "BG", label: "+359", name: "Bulgaria" },
  { code: "KH", label: "+855", name: "Cambodia" },
  { code: "CA", label: "+1", name: "Canada" },
  { code: "CL", label: "+56", name: "Chile" },
  { code: "CN", label: "+86", name: "China" },
  { code: "CO", label: "+57", name: "Colombia" },
  { code: "CR", label: "+506", name: "Costa Rica" },
  { code: "HR", label: "+385", name: "Croatia" },
  { code: "CY", label: "+357", name: "Cyprus" },
  { code: "CZ", label: "+420", name: "Czech Republic" },
  { code: "DK", label: "+45", name: "Denmark" },
  { code: "DO", label: "+1-809", name: "Dominican Republic" },
  { code: "EC", label: "+593", name: "Ecuador" },
  { code: "EG", label: "+20", name: "Egypt" },
  { code: "SV", label: "+503", name: "El Salvador" },
  { code: "EE", label: "+372", name: "Estonia" },
  { code: "FI", label: "+358", name: "Finland" },
  { code: "FR", label: "+33", name: "France" },
  { code: "GE", label: "+995", name: "Georgia" },
  { code: "DE", label: "+49", name: "Germany" },
  { code: "GH", label: "+233", name: "Ghana" },
  { code: "GR", label: "+30", name: "Greece" },
  { code: "GT", label: "+502", name: "Guatemala" },
  { code: "HK", label: "+852", name: "Hong Kong" },
  { code: "HU", label: "+36", name: "Hungary" },
  { code: "IS", label: "+354", name: "Iceland" },
  { code: "IN", label: "+91", name: "India" },
  { code: "ID", label: "+62", name: "Indonesia" },
  { code: "IR", label: "+98", name: "Iran" },
  { code: "IQ", label: "+964", name: "Iraq" },
  { code: "IE", label: "+353", name: "Ireland" },
  { code: "IL", label: "+972", name: "Israel" },
  { code: "IT", label: "+39", name: "Italy" },
  { code: "JP", label: "+81", name: "Japan" },
  { code: "JO", label: "+962", name: "Jordan" },
  { code: "KZ", label: "+7", name: "Kazakhstan" },
  { code: "KE", label: "+254", name: "Kenya" },
  { code: "KW", label: "+965", name: "Kuwait" },
  { code: "LV", label: "+371", name: "Latvia" },
  { code: "LB", label: "+961", name: "Lebanon" },
  { code: "LT", label: "+370", name: "Lithuania" },
  { code: "LU", label: "+352", name: "Luxembourg" },
  { code: "MY", label: "+60", name: "Malaysia" },
  { code: "MT", label: "+356", name: "Malta" },
  { code: "MX", label: "+52", name: "Mexico" },
  { code: "MA", label: "+212", name: "Morocco" },
  { code: "NL", label: "+31", name: "Netherlands" },
  { code: "NZ", label: "+64", name: "New Zealand" },
  { code: "NG", label: "+234", name: "Nigeria" },
  { code: "NO", label: "+47", name: "Norway" },
  { code: "OM", label: "+968", name: "Oman" },
  { code: "PK", label: "+92", name: "Pakistan" },
  { code: "PA", label: "+507", name: "Panama" },
  { code: "PY", label: "+595", name: "Paraguay" },
  { code: "PE", label: "+51", name: "Peru" },
  { code: "PH", label: "+63", name: "Philippines" },
  { code: "PL", label: "+48", name: "Poland" },
  { code: "PT", label: "+351", name: "Portugal" },
  { code: "QA", label: "+974", name: "Qatar" },
  { code: "RO", label: "+40", name: "Romania" },
  { code: "RU", label: "+7", name: "Russia" },
  { code: "SA", label: "+966", name: "Saudi Arabia" },
  { code: "RS", label: "+381", name: "Serbia" },
  { code: "SG", label: "+65", name: "Singapore" },
  { code: "SK", label: "+421", name: "Slovakia" },
  { code: "SI", label: "+386", name: "Slovenia" },
  { code: "ZA", label: "+27", name: "South Africa" },
  { code: "KR", label: "+82", name: "South Korea" },
  { code: "ES", label: "+34", name: "Spain" },
  { code: "LK", label: "+94", name: "Sri Lanka" },
  { code: "SE", label: "+46", name: "Sweden" },
  { code: "CH", label: "+41", name: "Switzerland" },
  { code: "TW", label: "+886", name: "Taiwan" },
  { code: "TH", label: "+66", name: "Thailand" },
  { code: "TN", label: "+216", name: "Tunisia" },
  { code: "TR", label: "+90", name: "Turkey" },
  { code: "UA", label: "+380", name: "Ukraine" },
  { code: "AE", label: "+971", name: "United Arab Emirates" },
  { code: "GB", label: "+44", name: "United Kingdom" },
  { code: "US", label: "+1", name: "United States" },
  { code: "UY", label: "+598", name: "Uruguay" },
  { code: "UZ", label: "+998", name: "Uzbekistan" },
  { code: "VE", label: "+58", name: "Venezuela" },
  { code: "VN", label: "+84", name: "Vietnam" },
];